version: '3'

services:
  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  keycloak:
    image: bitnami/keycloak:21.1.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_DATABASE_VENDOR: dev-file