server:
  port: 8090
  error:
    include-binding-errors: always
    include-message: always


spring:
  security:
    oauth2:
      client:
        registration:
          resource-server-client:
            client-id: spring-cloud-feign
            client-secret: doSjccFTL4c8KC82b8SqvOH9h1viss3v
            authorization-grant-type: client_credentials
        provider:
          resource-server-client:
            token-uri: http://localhost:8080/realms/dev/protocol/openid-connect/token

client-app:
  application-name: "client-app"
  scheduller:
    send-message-scheduller: 0 * * * * * # every minute
  feign-properties:
    registration-id: resource-server-client
    logger-level: FULL
    feign-retryer:
      start-interval: 100
      max-interval: 3000
      attempts: 5
    resource-server:
      url: http://localhost:9095/api/v1

logging:
  level:
    root: INFO
